version: '2.0'

services:

  #------------------------------------------------------------------
  # Volumes
  #------------------------------------------------------------------

  volume_media:
    container_name: minerva_media
    image: tianon/true
    environment:
      PGID: ${MINERVA_CONFIG_PGID}
      PUID: ${MINERVA_CONFIG_PUID}
    volumes:
      - ${MINERVA_LOCATION_TORRENT_DOWNLOADS}:/downloads
      - ${MINERVA_LOCATION_TORRENT_WATCH}:/watch
      - ${MINERVA_LOCATION_TVSHOWS}:/tv
      - ${MINERVA_LOCATION_MOVIES}:/movies

  #------------------------------------------------------------------
  # Services
  #------------------------------------------------------------------
  transmission:
    container_name: minerva_transmission
    image: linuxserver/transmission
    hostname: ${MINERVA_NETWORK_TRANSMISSION_HOSTNAME}
    networks:
      minerva:
        aliases:
          - ${MINERVA_NETWORK_TRANSMISSION_HOSTNAME}
    ports:
      - 9091:9091
    environment:
      PGID: ${MINERVA_CONFIG_PGID}
      PUID: ${MINERVA_CONFIG_PUID}
    volumes:
      - ${HOME}/.Minerva/config/transmission:/config
    volumes_from:
      - volume_media

  sonarr:
    container_name: minerva_sonarr
    image: linuxserver/sonarr
    hostname: ${MINERVA_NETWORK_SONARR_HOSTNAME}
    networks:
      minerva:
        aliases:
          - ${MINERVA_NETWORK_SONARR_HOSTNAME}
    ports:
      - 8989:8989
    environment:
      PGID: ${MINERVA_CONFIG_PGID}
      PUID: ${MINERVA_CONFIG_PUID}
    volumes:
      - ${HOME}/.Minerva/config/sonarr:/config
    volumes_from:
      - volume_media

  radarr:
    container_name: minerva_radarr
    image: linuxserver/radarr
    hostname: ${MINERVA_NETWORK_RADARR_HOSTNAME}
    networks:
      minerva:
        aliases:
          - ${MINERVA_NETWORK_RADARR_HOSTNAME}
    ports:
      - 7878:7878
    environment:
      PGID: ${MINERVA_CONFIG_PGID}
      PUID: ${MINERVA_CONFIG_PUID}
    volumes:
      - ${HOME}/.Minerva/config/radarr:/config
    volumes_from:
      - volume_media

  plex:
    container_name: minerva_plex
    image: linuxserver/plex
    hostname: ${MINERVA_NETWORK_PLEX_HOSTNAME}
    networks:
      minerva:
        aliases:
          - ${MINERVA_NETWORK_PLEX_HOSTNAME}
    ports:
      - 3005:3005
      - 32400:32400
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
      - 8324:8324
    environment:
      PGID: ${MINERVA_CONFIG_PGID}
      PUID: ${MINERVA_CONFIG_PUID}
    volumes:
      - ${HOME}/.Minerva/config/plex:/config
      - ${HOME}/.Minerva/transcode:/transcode
    volumes_from:
      - volume_media

networks:
  minerva:
