version: '2.0'

services:

  #------------------------------------------------------------------
  # Volumes
  #------------------------------------------------------------------

  volume_media:
    container_name: minerva_media
    image: tianon/true
    network_mode: host
    environment:
      PGID: ${MINERVA_CONFIG_PGID}
      PUID: ${MINERVA_CONFIG_PUID}
    volumes:
      - ${MINERVA_LOCATION_TORRENT_DOWNLOADS}:/downloads
      - ${MINERVA_LOCATION_TORRENT_WATCH}:/watch
      - ${MINERVA_LOCATION_TVSHOWS}:/tv
      - ${MINERVA_LOCATION_MOVIES}:/movies

  #------------------------------------------------------------------
  # Services
  #------------------------------------------------------------------
  transmission:
    container_name: minerva_transmission
    image: linuxserver/transmission
    network_mode: host
    hostname: ${MINERVA_NETWORK_TRANSMISSION_HOSTNAME}
    environment:
      PGID: ${MINERVA_CONFIG_PGID}
      PUID: ${MINERVA_CONFIG_PUID}
    volumes:
      - ${HOME}/.Minerva/config/transmission:/config
    volumes_from:
      - volume_media

  sonarr:
    container_name: minerva_sonarr
    image: linuxserver/sonarr
    network_mode: host
    hostname: ${MINERVA_NETWORK_SONARR_HOSTNAME}
    environment:
      PGID: ${MINERVA_CONFIG_PGID}
      PUID: ${MINERVA_CONFIG_PUID}
    volumes:
      - ${HOME}/.Minerva/config/sonarr:/config
    volumes_from:
      - volume_media

  radarr:
    container_name: minerva_radarr
    image: linuxserver/radarr
    network_mode: host
    hostname: ${MINERVA_NETWORK_RADARR_HOSTNAME}
    environment:
      PGID: ${MINERVA_CONFIG_PGID}
      PUID: ${MINERVA_CONFIG_PUID}
    volumes:
      - ${HOME}/.Minerva/config/radarr:/config
    volumes_from:
      - volume_media

  plex:
    container_name: minerva_plex
    image: linuxserver/plex
    hostname: ${MINERVA_NETWORK_PLEX_HOSTNAME}
    network_mode: host
    environment:
      PGID: ${MINERVA_CONFIG_PGID}
      PUID: ${MINERVA_CONFIG_PUID}
    volumes:
      - ${HOME}/.Minerva/config/plex:/config
      - ${HOME}/.Minerva/transcode:/transcode
    volumes_from:
      - volume_media
